### ISSUE TITLE
Could not find a version that satisfies the requirement vtk<9.1.0

### ISSUE THREAD

**Issue by pglelievre** [marcomusy/vedo#685]
I had been getting an error message when trying to add a scale bar to one of my plots:

> Traceback (most recent call last):
>   File "/Users/plelievre/Work/Research/Current/FloodRiskManagement/Code/Python/show3dinvslice_x.py", line 25, in <module>
>     box_msh.addScalarBar3D(title = 'Resistivity (\Omegam)', titleSize = 3, titleRotation = 180, titleXOffset = 2, labelSize = 3, pos = (17, 4.3, 9), s = (1, 8.), drawBox = True)
> TypeError: BaseActor.addScalarBar3D() got an unexpected keyword argument 's'

To me that looked like perhaps the 's' argument was a newer option, and I realized that I was running an older version of vedo, so I tried updating to the most recent version of vedo using:

> pip install -U git+https://github.com/marcomusy/vedo.git

I'm on macOS 12.5.1 (Monterey) and running a couple versions of python. I have no problem on python 3.7.11 + latest version of vedo. However, python 3.10.6 complains when I try to install the latest version of vedo as above. The error message is:

> ERROR: Could not find a version that satisfies the requirement vtk<9.1.0 (from vedo) (from versions: 9.2.0rc1, 9.2.0rc2)
> ERROR: No matching distribution found for vtk<9.1.0

**Comment by marcomusy** [comment]
hi, `vedo` works best with vtk9.1 but it also works ok with vtk9.2, you can override it with
`pip install vedo -U --no-deps`
